// Database.jsx

export const issueListAll = [
  "BDIX",
  "CDN",
  "Client Visit",
  "FNA",
  "Follow Up",
  "FTP Server",
  "Gaming",
  "GGC",
  "IMO",
  "Info",
  "INT",
  "Link Down",
  "Mac Clear",
  "MKT Conf",
  "OLT Conf.",
  "ONU Conf.",
  "Others",
  "Packet Loss",
  "Recharge",
  "Slow",
  "Upload",
  "User Create",
  "Website",
  "Switch Configuration",
  "New Physical Link Installation"
];

export const clientListAll = [
  "Gopalpur Bazar",
  "Dream.Net",
  "2280_AF Friends cable Network",
  "2280_AF Network_3",
  "3Star Network",
  "4Star Maijdee 4star@Maij   HTL20364",
  "AB Online-Netrokona Ab@Online   HTL22334",
  "Abraham Broadband (Masum)",
  "Achol Internet",
  "Active Internet Service Active@Int   HTL22984",
  "AD Internet Service",
  "Adel Online",
  "AF Bander net",
  "AF Internet Rb Broadband",
  "AF Internet Zone AF@Inter25#   HTL22977",
  "AF Jahir",
  "AF RB net",
  "AF Rony cable",
  "AF_AKRAM",
  "AirNet Cable Systems",
  "AJM Satellite Vision",
  "AK Wifi",
  "Akota Net",
  "Al Amin Enterprise",
  "Al Amin Online",
  "Alamgir Cable with Asiatel",
  "Alamin_Ent",
  "Alekgender Monir POP",
  "Alekgender Monir POP Alekgen@Monir   HTL11137",
  "Alfa Net CTG",
  "Alfa Online",
  "Alif Communication Alif@com   HTL8255",
  "Alishor Online",
  "Alo Online",
  "Alomgir cable Network",
  "Amaan Cable Network",
  "Amazing Online",
  "Anas Network",
  "Angel online",
  "Anik Broadband",
  "Anita tred international &  cable network",
  "ANL Maijdee with Saudia Satelite",
  "Antaranga Dot Com CTG",
  "Anu Ambia",
  "Anu Ambia-2",
  "Anu Ambia-3",
  "Apon Computer Training Institute",
  "AR Discovery",
  "AR First Network",
  "Arab Cable Network",
  "Asadpur Broadband Internet Service",
  "Ashraf Online Gazipur",
  "Asia cable network",
  "Asia-Cable-Network-F@H",
  "Asiatel Network-Konabari Konabari@sahid   HTL2824",
  "Asiatel Network-Konabari-Sajib Sajib@konabari   HTL10651",
  "Asiatel-Network-Natore Natore@Fahim   HTL2825",
  "Asif_Chowrasta-Skynet",
  "ATS Cable Network",
  "Azad-Broadband-MAC",
  "Badda Cable Connection",
  "Baghmara POP All Client",
  "Baijid Broadband",
  "Baizid Online",
  "Bakhrabad Cable Network",
  "Bakoi pop lalmai",
  "Bancharampur Cable Network",
  "Banglabazar Home User",
  "Banglabazar Shanto",
  "Banglabazar, Arman",
  "Barnil Network",
  "Barogao POP Monir",
  "Bashikpur Monir_POP",
  "Basurhat POP Kamal Basurhat@pop   HTL20779",
  "Basurhatt Pop Kamal",
  "BD Connet CTG",
  "BD HUB",
  "BD Net Dolta",
  "Bhai Bhai Cable",
  "Bhai Bhai WiFi Service (Chaklaxmipur)",
  "Bijoypur Internet",
  "Bijoypur Online",
  "Bina_Cable_Network Bina@cable   HTL1934",
  "BlueNet",
  "Bondhon Internet",
  "BONGSHIBAZAR-ONLINE",
  "Boshikpur Pop Monir",
  "Bosurhat Broadband",
  "Bosurhut SuperNet",
  "Brothers ICT Connectivity",
  "Brothers_Cable (BCN)",
  "BS Online",
  "BSW Network",
  "CCL Velocity",
  "CCS Dhalirghat",
  "CCS Mashnigacha",
  "CCS Nayonnet",
  "CCS Nurpur",
  "CCS Rahimanagar",
  "CCS Staronline",
  "CCS_BEPARI_BAZAR",
  "CCS_BURGI",
  "CCS_Chandpur",
  "CCS_EKBARIA",
  "CCS_Hosenpur",
  "CCS_Kazi",
  "CHANDINA ONLINE MADHAYA",
  "Chandpur - Home User",
  "Chandpur Pop Jubayer",
  "Chandpur Pop Rony NTTN",
  "Chandpur Pop Rony OH",
  "Chapitola Adhor",
  "Chapitola Adhor_2",
  "Chatkhil Pop Titu Bhai",
  "Chatkhil POP Titu Bhai (Bandwidth)",
  "Chhagalnaiya Home User",
  "CIP_Net Chatkhil",
  "City Broadband",
  "Cloud Online.",
  "CNF-Network",
  "Companigonj WiFi Network",
  "Connect 3",
  "Corporate Customer (All)",
  "Creativa IT",
  "Cyber Cable Network",
  "Cyber Net Communication",
  "D-Smart",
  "Daghanbhuiyan_Home User",
  "Dagonbhuiyan Pop Rubel",
  "Dagonbhuiyan Pop Rubel Dagon@Rubel   HTL22948",
  "Dagonbyuiyan Pop Rubel(ROYAL BROADBAND NOAKHALI)",
  "Dalal Bazar Joshim",
  "Dark Online",
  "Daud Poshuram",
  "Daudkanddi Tuhin POP",
  "Daudkanddi Tuhin POP-2",
  "Daulatganj Mudafforgonj support",
  "Debiddar Ali POP",
  "Debiddar Ali POP-3",
  "Debiddar Hasan POP",
  "Debidwar Z Online",
  "Debpur Online",
  "Debuttar-Pabna",
  "Dhanshalik Network",
  "Dhattapara Online",
  "Dhumketu WiFi",
  "Diganta Net (Raozan)",
  "Diganta Net CTG",
  "Dighirjan POP Arafat",
  "Digi Jadoo Broadband Limited",
  "Digital Cable Network  Digital@cable   HTL8339",
  "Digital Communication BD",
  "Digital Communication BD",
  "Digital Communication Tasfia Online Debidwar Ali POP",
  "Digital Communication-Ashiqur _NHK",
  "Digital Internet",
  "Digital Shadin Wifi Digital@wifi   HTL29245",
  "Dolta_Bazar Juwel",
  "Dolta_Hellal",
  "Dolta_Rashed",
  "Dot Internet DHK",
  "Dot Net Online",
  "DOTTER-HAT-ONLINE",
  "Doulatgonj Online",
  "Dream line Skynet Unit-02",
  "Dream Satelite",
  "Duranta Network Duranta@net   HTL7119",
  "Durontto Network",
  "Easy Net",
  "Emon Cable Network",
  "Faizan Cable",
  "Farah Dot Com",
  "Faridgonj Broadband",
  "Faridgonj WiFi & Broadband",
  "Farifgonj_Rana",
  "Farjana Cable",
  "Fast Internet",
  "Fast Net Maijdee",
  "Fast Network",
  "Faysal Cable Network||HTL-DHK-MAC-F@H",
  "FC BROADBAND",
  "FCN Online FCN@Online   HTL6272",
  "Feni Hajari Road",
  "Feni pop Amdad",
  "Feni Pop Jahid",
  "Feni Pop KHAN",
  "Feni_Home_User",
  "Feni_Home_User",
  "Feni.com",
  "Fiber Connect",
  "Fiber Net",
  "Fiber Point",
  "FNS Network",
  "Freedom Fighter Online ( KR Online)",
  "Friends Cable Network",
  "Friends Network-Satkhira",
  "Friends Online Korihati",
  "Friends Wifi",
  "Fulgazi Pop Sishir",
  "Fulgazi vision",
  "Full Gazi Cable Network",
  "G Network-MAC-HTL-DHK-F@H-Gazipur",
  "Gabtola Internet Service",
  "Galaxy Net",
  "Genfive Techonology",
  "Gitacaldiya Faysal POP",
  "Golden Online",
  "Gomti Network",
  "Goni Communication",
  "Haiderganj Online",
  "Harun_Online",
  "Hazari Online",
  "Hazigonj Online",
  "Hellotech-RF_Bhauksar",
  "Hingula Online",
  "HomeNet Solutions",
  "Homna Online",
  "HORICHOR ONLINE",
  "HP Link",
  "HTA Network",
  "HTL-Friend Cable Network Cable@Net25   HTL28236",
  "IB NET",
  "ICT Mart BD",
  "Imam Cable Network Imam@Cable   HTL29264",
  "Impex BD Net",
  "Info.com",
  "Insaf Online",
  "INTERLINK COMMUNICATION",
  "Interlink-Communication",
  "IQ Tel Network CTG",
  "J.R. Broadband Internet Service",
  "J.S.S Network",
  "JA Internet",
  "Jaaj communication",
  "Jabir Internet Cable Service",
  "Jakshin Pop",
  "Jakshin PoP Sahed",
  "JB Internet",
  "JH Online (Jahir Bhai)",
  "Jirtoli Pop Tutul",
  "Jitu Satellite",
  "Josh-Internet",
  "JS Online",
  "JSS Network BHN CCL",
  "Jubayed Wifi",
  "Junayed online",
  "Kachua Pop Babul",
  "Kalibazar_Home_User",
  "Kalibazer Home User",
  "Kalir Bazar Home User",
  "Kamal Vision Network",
  "Kashinagar Salam",
  "Kashipur Home User",
  "Kashipur pop Monir Bhai",
  "Khan Internet",
  "Khilbaicha Pop",
  "Khokon Online Barura",
  "Khokon Online Khokon@online25   HTL22495",
  "King It Net",
  "komolnagar arif",
  "KORAIS MUNSHI BAZER",
  "Laxminarayanpur_POP",
  "Laxmipur_Home_user",
  "Laxmipur_POP_Parvej",
  "Link-10",
  "Lions Network Limited Lions@Net   HTL4038",
  "LJ Broadband",
  "LJ Broadbrand Madanpur",
  "M.S.MUKTIJUDDA WIFI",
  "M/S M Hoque Ent. Hoque@Ent25   HTL22913",
  "M/S Speed Link_Dhaka",
  "M&F Internet",
  "M&F_Network M&F   HTL4095",
  "Madaiya Online With Skynet",
  "Madhaya Online",
  "Madhaya Online Madhaya@online   HTL10663",
  "Mahera Cable Network Mahera@net   HTL12588",
  "Maijdee Supernet",
  "Mandari Online",
  "Master_Network",
  "Masum Broadband Internet",
  "Mawa Online",
  "Maxim Software Bill Collection",
  "Maxline IT",
  "Mayeen_Doulatpur",
  "Mayerdoya Satellite",
  "Mazeda Network",
  "MC Broadband",
  "Meghna Broadband",
  "Megna Broadband, Megna-1",
  "Megna-2(Yasir Online) |SNC-MAC",
  "Melkar-Internet",
  "Mihad Cable wifi Network",
  "Milon Wifi Khilpara",
  "Mir dot com",
  "Mira Technology",
  "Mirerpol, Dudmukha",
  "Mission Computer",
  "Miyarhat Cable Network",
  "MK NETWORK_Munshigonj",
  "Mohipal_Vision",
  "Mohonpur Broadband Internet services",
  "Mohonpur_Wifi_Network",
  "Momota Technology",
  "Moon Cable Network",
  "Moon Online Sultanpur (RAJGONJ_POP)",
  "Mostak Online",
  "Moulovibazar-Network",
  "Mridha corporation (Dhamura)",
  "Mridha Corporation Patuakhali",
  "MRT Broadband _ Jamidarhatt Pop",
  "Munshirhatt WiFi",
  "My Net",
  "My Net Wifi",
  "Nabila Kawser cable Net",
  "Narayangonj Aggregate Bahon Clients",
  "Nazmul_Tangail Nazmul@HT   HTL2728",
  "NG Net",
  "Nishamoni_Wifi",
  "Noah Internet",
  "Noborupa _Kochua Broadband",
  "Noborupa Cable Network",
  "Novus Network",
  "Nuapara Online",
  "Nuralam_Sonaimuri",
  "OCN-Network-DHK-SCL-MAC",
  "Omar Network",
  "Optimus Online",
  "Orbit Plus  Orbit@plus   HTL9594",
  "Othoi Online Othoi@online   HTL33506",
  "Panchomy Network",
  "Patwary Communication",
  "Patwary Net Faridgonj",
  "Play Cable Network  Play@Cable   HTL8352",
  "Plusnet CTG",
  "Poddokot Cable Network",
  "Polli Net Maijdee",
  "Polli Network,Hazirhat",
  "Poshuram Kamrul",
  "Prince Online Lalmai",
  "Priya Cable Laxmipur",
  "Rabbit Internet-CTG",
  "Rahika Enterprise",
  "Rakhaliya Online",
  "Ramgonj Online Rased",
  "Ramgonj_POP_Robi",
  "Ramgoti Pop",
  "Ramjan_BiBi_POP-Yeasin",
  "RANA Faridgonj",
  "RAS Online",
  "Rasel Enterprise  Rasel@Ent   HTL10646",
  "Raypur POP Shain",
  "Raypur pop Sishir",
  "RB Online RB@online   HTL20555",
  "Red Zone Online",
  "Rego Communication",
  "RF IT Place",
  "RF khan net",
  "RF Mintu",
  "RF Online",
  "RF Online Shahrasti",
  "RF Online Shahrasti",
  "RF Online Shahrasti",
  "RF Sohag",
  "RF_Anisur",
  "RF_Bakila",
  "Robi Ramgonj",
  "Robin_Cable",
  "Rongdhonu Online",
  "RONGDHONU ONLINE-2",
  "Rongdhonu-Miabazar-Habib",
  "Rony Cable Network",
  "Rony Online",
  "RS Network",
  "Rubel Online",
  "Ruhul Communication",
  "Rural-Network-System",
  "S.M Online Cable",
  "S.M Online Cable",
  "Sahadebpur Sanjib POP",
  "Saif Online",
  "Samir Broadband",
  "Samiya Net",
  "SAUDIA SATELLITE INTERNET MOTIPUR",
  "SB Cable network",
  "SB Net City",
  "SB Technology",
  "SBS Network -Tangail",
  "SBS Network -Tangail with Asiatel",
  "Seba Nit",
  "Sebarhatt Pop Sahadat",
  "SF Internet",
  "Sha alam Cable Network",
  "SHAHADAT CABLE",
  "Shimu Internet Service Network",
  "Shopno Cable Network",
  "SI Fiber Net",
  "SI Net,Khulna",
  "Siam Online Kalir Bazar",
  "Sine10",
  "Sixty four Network Ltd",
  "Siyum Enterprise",
  "SK Communication",
  "SK Net City",
  "Skylark Network",
  "Skylink Communication",
  "Skynet AF Internet",
  "Skynet Broadband Service",
  "Skynet ERP (Senbag",
  "Skynet Support Vai Vai",
  "Skynet_Ramgonj",
  "Skytel Communication Ltd.",
  "SM Network",
  "SM_Internet_Network",
  "SMCN-Alamgir Hossen SMCN@Hossen   HTL14344",
  "SMCN-Alamgir Smcn@Alamgir   HTL14338",
  "SMCN-Asad smcn@asad   HTL14343",
  "SMCN-Bablu SMCN@Bablu   HTL14863",
  "SMCN-Babu smcn@babu   HTL15014",
  "SMCN-Belal smcn@belal   HTL14860",
  "SMCN-Ekbal smcn@ekbal   HTL14915",
  "SMCN-Iqbal Hossen SMCN@Iqbal   HTL14828",
  "SMCN-Jahed SMCN@Jahed   HTL14864",
  "SMCN-Jahidul Islam SMCN@Jahidul   HTL14824",
  "SMCN-Joynal Abadin Smcn@Joynal   HTL14272",
  "SMCN-Joynal smcn@joynalabedin   HTL14910",
  "SMCN-Kalam smcn@kalam   HTL14916",
  "SMCN-Kanu Barua SMCN@KanuBarua   HTL14345",
  "SMCN-Khokan SMCN@Khokan   HTL14913",
  "SMCN-Korban Ali SMCN@Korbanali   HTL14859",
  "SMCN-Lalu SMC@Lalu   HTL14829",
  "SMCN-Mahabubur-Rahaman  SMCN@Roket   HTL14339",
  "SMCN-Mainul(Notun Para) smcn@mainul   HTL14827",
  "SMCN-Masud (Nizampur) smcn@masud   HTL15012",
  "SMCN-Md Forhad SMCN@Forhad   HTL14862",
  "SMCN-Md. Saiful Smcn@Saiful   HTL14208",
  "SMCN-Mohammed Shoed Smcn@shoed   HTL14340",
  "SMCN-Najim SMCN@Najim   HTL14826",
  "SMCN-Nobi smcn@nobi   HTL14347",
  "SMCN-Nona Smcn@nona   HTL17320",
  "SMCN-Nur Nobi SMCN@Nurnobi   HTL14830",
  "SMCN-Rasel SMCN@Rasel   HTL14858",
  "SMCN-Sabuj Sen smcn@Sabuj   HTL14914",
  "SMCN-Sakawyat SMCN@Sakawyat   HTL14346",
  "SMCN-Salim Uddin(Fedainogor) Smcn@Salim   HTL14303",
  "SMCN-Shadat SMCN@Shadat   HTL14912",
  "SMCN-Sobuj Chowdhuri smcn@sobuj   HTL14857",
  "SMCN-Sotota SMCN@Sotota   HTL14341",
  "SMCN-Sukanta SMCN@Office   HTL14909",
  "SMCN-Sumit Sen smcn@sumit   HTL14911",
  "SMCN-Sumon smcn@sumon   HTL15013",
  "SMCN-Tapos smcn@tapos   HTL14825",
  "SMCN-Titu SMCN@Titu   HTL14861",
  "Smirity Cable Internet Service Provider",
  "SNM_SONIMURI",
  "Sobuj sathi Feni",
  "Sojib Cable Network Sojib@Cable   HTL7728",
  "Solimabad_Online",
  "Sonali Online (MAC)",
  "SOURCE_NET_BHOLA source_net   HTL1791",
  "Speed Link Manda Naogaon",
  "Speed Net",
  "Speed_Link SpeedLink@Manda   HTL4039",
  "SS Net Chowdhury hat",
  "SS NETWORK",
  "SS Online",
  "SS-NET-SONAPUR",
  "SSB ONLINE",
  "SST-Azim Uddin azimbutpar   HTL13865",
  "SST-Based Keramot basedkeramot   HTL13826",
  "SST-Bellal Bellal005   HTL13118",
  "SST-Firoz firoz007   HTL13818",
  "SST-Milon Milon@tangail   HTL13226",
  "SST-Moni moni001   HTL12593",
  "SST-Omar Network Main Omar@main   HTL27940",
  "SST-Omor Faruk Omor@Faruk   HTL13951",
  "SST-Pakutia Net Pakutia@Net   HTL22922",
  "SST-Shafiqul Shafiqul@net   HTL13277",
  "SST-Shanto santo004   HTL12745",
  "SST-Sumon Saha Sumon_Saha   HTL13978",
  "SST-Tahsin- MAC Service- Tangail",
  "SST-Tangail Shorif@Tangail   HTL12772",
  "SST-Thasin Thasin@2025   HTL13372",
  "SST. Arshi Porshi || HTL-DHK-MAC",
  "ST Network Ramprasad",
  "Star Cable Network",
  "Star Net Noakhali Star@Net25   HTL22951",
  "Star Network",
  "Star Online CTG",
  "STAR ONLINE RAMJANBIBI",
  "Star_BD_Lalmonirhat star@bd   HTL1790",
  "Stardust Telecommunication LTD",
  "Starlink Communication",
  "Suchona Broadband",
  "Sujon IT",
  "Sultanpur Online",
  "Super Net Basurhat",
  "Super Net Senbug",
  "Super Net Senbug Delower",
  "TA Online Foridgonj",
  "Tangail Online",
  "Tariqul Computer & Internet Point",
  "The Khan Internet",
  "Three Dot Net DHK",
  "Three Star Amjad",
  "Tokchanpur Wifi-Tangail Tokchan@wifi   HTL10442",
  "Tomato Web",
  "Tomijuddin Rasulgonj",
  "Top Network",
  "Top Online Chatkhil",
  "Top Online Chatkhil (New)",
  "TR Online Raypur",
  "Triple E Online",
  "Trusted Internet",
  "Tulatoli POP Anam",
  "Turbo Internet",
  "UNIQUE ONLINE LAXMINARAYONPUR",
  "United Net",
  "UpNet Feni",
  "Vai Vai Cable Network mdmasudsonia   HTL4040",
  "Vai Vai Cable with Asiatel",
  "Vatialpur Akram",
  "Vhuter Bari Cable Network",
  "Weblink Communications Ltd.",
  "Wifi zone",
  "Yeasin Broadband Megna-2",
  "Yeasin Cable Network",
  "Yeasin online",
  "Yousuf_Online",
  "Z-SPEED-NET-SONAPUR",
  "Zakia_Online",
  "Porshuram Kamrul",
  "ANL_Maijdee With Italy Broadband",
  "Amratuli online"
];
